name: spectraf
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - numpy>=1.20
  - rasterio>=1.2
  - matplotlib>=3.3
  - geopandas>=0.10
  - scipy>=1.7
  - shapely>=1.8
  - pyproj>=3.0
  - pip
